[package]
name = "const-pki-types"
description = "Converting X.509 certificates to the TrustAnchor in rustls-pki-types at compile time"
version = "0.0.0"
edition = "2024"

[dependencies]
rustls-pki-types = { version = "1.13.1", default-features = false }

[dev-dependencies]
webpki-root-certs = "1.0.4"
webpki-roots = "1.0.4"
